- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0  # Use the ref you want to point at
  hooks:
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
- repo: https://github.com/pycqa/isort
  rev: 5.11.2
  hooks:
  - id: isort
    name: isort (python)